# Generated by Django 5.1.6 on 2025-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='potencia_watts',
            new_name='potencia',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Manutenção', 'Manutenção')], default='Inativo', max_length=20),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ultima_leitura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
