# Generated by Django 5.1.6 on 2025-08-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_rename_potencia_watts_equipamento_potencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='horas_uso_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='potencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
