# Generated by Django 5.1.7 on 2025-05-24 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
