# Generated by Django 5.2.4 on 2025-08-01 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leituras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paga', models.BooleanField(default=False)),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leituras.leitura')),
            ],
        ),
    ]
