# Generated by Django 5.1.6 on 2025-09-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='matricula.matricula')),
            ],
        ),
    ]
