# Generated by Django 5.1.6 on 2025-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
