# Generated by Django 5.2.4 on 2025-08-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.medidor')),
            ],
        ),
    ]
